import { LegalLayout } from "@/components/layout/LegalLayout";

export default function TermsOfService() {
    return (
        <LegalLayout title="Terms of Service" date="January 1, 2025">
            <section>
                <h2 className="text-2xl font-semibold text-white mb-4">Clinical Decision Support Tool</h2>
                <p>
                    Stellar Infomatica's prenatal screening software is provided as a Clinical Decision Support (CDS) tool designed to assist qualified pathology professionals in the interpretation of biomarker data and risk calculations. This software is not intended to replace professional medical judgment, clinical expertise, or comprehensive patient evaluation. All results generated by the software must be reviewed, validated, and interpreted by licensed healthcare providers with appropriate training in prenatal screening and cytogenetics.
                </p>
                <p>
                    The software performs mathematical calculations based on established algorithms for dual marker, triple marker, and quad marker screening protocols. It provides risk assessments for chromosomal abnormalities, including Down syndrome (Trisomy 21), Edwards syndrome (Trisomy 18), and neural tube defects. These calculations are derived from peer-reviewed research and validated screening protocols, but they represent statistical probabilities, not definitive diagnoses.
                </p>
            </section>

            <section>
                <h2 className="text-2xl font-semibold text-white mb-4">Twin Pregnancy Risk Calculations</h2>
                <p>
                    Our software includes specialized algorithms for twin pregnancy screening, which account for the unique physiological characteristics of multiple gestations. The "Twin Risk" calculations provided by the software are based on modified risk algorithms that adjust for the presence of multiple fetuses. However, these calculations are inherently more complex than singleton pregnancies and may have different sensitivity and specificity characteristics.
                </p>
                <p>
                    Stellar Infomatica expressly disclaims any liability for clinical decisions made based on twin risk calculations or any other outputs from the software. The interpretation of screening results, determination of follow-up testing, and patient counseling decisions remain the sole responsibility of the ordering physician and the laboratory director. Users must exercise independent clinical judgment and consider all relevant patient factors, including family history, ultrasound findings, and other diagnostic information.
                </p>
            </section>

            <section>
                <h2 className="text-2xl font-semibold text-white mb-4">Limitation of Liability</h2>
                <p>
                    To the maximum extent permitted by law, Stellar Infomatica shall not be liable for any direct, indirect, incidental, special, consequential, or punitive damages arising from the use or inability to use this software, including but not limited to medical malpractice claims, diagnostic errors, or adverse patient outcomes. The software is provided "as is" without warranties of any kind, either express or implied, including but not limited to warranties of merchantability, fitness for a particular purpose, or accuracy of calculations.
                </p>
                <p>
                    By using this software, you acknowledge that you are a qualified healthcare professional or authorized representative of a licensed medical facility. You agree to use the software in accordance with all applicable laws, regulations, and professional standards. Stellar Infomatica reserves the right to modify, update, or discontinue features of the software with reasonable notice, but we are not obligated to provide ongoing support or updates unless specified in a separate service agreement.
                </p>
            </section>
        </LegalLayout>
    );
}

